"""Static checks requiring generated training scripts to use an LR schedule.

The AOI scripts are generated by an LLM, so this validator intentionally checks
for concrete executable structure rather than comments: a PyTorch lr_scheduler
must be constructed and the scheduler must be stepped from the training loop.
"""

from __future__ import annotations

import ast
from typing import Any


_KNOWN_SCHEDULERS = {
    "CosineAnnealingLR",
    "CosineAnnealingWarmRestarts",
    "CyclicLR",
    "ExponentialLR",
    "LambdaLR",
    "LinearLR",
    "MultiStepLR",
    "OneCycleLR",
    "ReduceLROnPlateau",
    "SequentialLR",
    "StepLR",
}


def _call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        prefix = _call_name(node.value)
        return f"{prefix}.{node.attr}" if prefix else node.attr
    return ""


def _assigned_names(node: ast.AST) -> list[str]:
    if isinstance(node, ast.Name):
        return [node.id]
    if isinstance(node, (ast.Tuple, ast.List)):
        names: list[str] = []
        for elt in node.elts:
            names.extend(_assigned_names(elt))
        return names
    return []


def _scheduler_class_name(call_name: str) -> str | None:
    short_name = call_name.split(".")[-1]
    if "lr_scheduler" in call_name or short_name in _KNOWN_SCHEDULERS:
        return short_name
    return None


def validate_lr_schedule_source(script: str) -> dict[str, Any]:
    """Return whether ``script`` constructs and steps a PyTorch LR scheduler."""
    try:
        tree = ast.parse(script)
    except SyntaxError as exc:
        return {
            "ok": False,
            "reasons": ["syntax_error"],
            "messages": [f"syntax error: {exc}"],
            "constructs_lr_scheduler": False,
            "calls_scheduler_step": False,
            "scheduler_classes": [],
            "scheduler_variables": [],
        }

    scheduler_classes: list[str] = []
    scheduler_vars: set[str] = set()

    for node in ast.walk(tree):
        value = None
        targets: list[ast.AST] = []
        if isinstance(node, ast.Assign):
            value = node.value
            targets = list(node.targets)
        elif isinstance(node, ast.AnnAssign):
            value = node.value
            targets = [node.target]

        if not isinstance(value, ast.Call):
            continue

        class_name = _scheduler_class_name(_call_name(value.func))
        if class_name is None:
            continue

        scheduler_classes.append(class_name)
        for target in targets:
            scheduler_vars.update(_assigned_names(target))

    has_scheduler_step = False
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Attribute) or node.func.attr != "step":
            continue
        owner = _call_name(node.func.value)
        if owner in scheduler_vars or owner.lower().endswith("scheduler"):
            has_scheduler_step = True
            break

    reasons: list[str] = []
    messages: list[str] = []
    if not scheduler_classes:
        reasons.append("missing_lr_scheduler")
        messages.append("no learning-rate scheduler constructed")
    if not has_scheduler_step:
        reasons.append("missing_scheduler_step")
        messages.append("scheduler.step() is not called")

    return {
        "ok": not reasons,
        "reasons": reasons,
        "messages": messages,
        "constructs_lr_scheduler": bool(scheduler_classes),
        "calls_scheduler_step": has_scheduler_step,
        "scheduler_classes": scheduler_classes,
        "scheduler_variables": sorted(scheduler_vars),
    }
