"""nodes/phase2_evaluator.py — Phase 2 Evaluator Node.

Sub-steps:
  4.8.1 Check validation cache (SHA-256 of script)
  4.8.2 Run via code_runner; parse metrics with metric_guard; reject degenerate outputs
  4.8.4 is_acceptance_improvement comparison; update CKPT_BEST_PIPELINE + best_* snapshot if improved
  4.8.7 Manage inner_iteration, no_improve_count; set stop_outer_loop = True when outer exit conditions met
  4.8.8 Return {latest_metrics, inner_iteration, no_improve_count, best_pipeline_script, best_*snapshot, stop_outer_loop}
"""

from __future__ import annotations

import logging
from typing import Any

from mle_star_agent import config
from mle_star_agent.guards.code_validator import check_validation_cache, store_validation_cache
from mle_star_agent.shared.acceptance_scoring import (
    is_acceptance_improvement,
    passes_final_acceptance,
)
from mle_star_agent.shared.checkpoint_io import save_checkpoint
from mle_star_agent.shared.code_runner import run_script
from mle_star_agent.shared.metric_guard import guard_metrics
from mle_star_agent.shared.metrics_parser import metrics_to_dict, parse_metrics
from mle_star_agent.shared.aoi_smoke_triage import build_smoke_diagnostics
from mle_star_agent.state import AgentState

logger = logging.getLogger(__name__)

def phase2_evaluator_node(state: AgentState) -> dict[str, Any]:
    """Phase 2 evaluator node.

    Evaluates the candidates generated by the coder, parsing metrics and updating the best state.
    """
    candidate_scripts = state.get("candidate_scripts", [])
    if not candidate_scripts:
        logger.warning("No candidate scripts provided to evaluator.")
        # Increment counters and return
        inner_iteration = state.get("inner_iteration", 0) + 1
        no_improve_count = state.get("no_improve_count", 0) + 1
        return {
            "inner_iteration": inner_iteration,
            "no_improve_count": no_improve_count,
        }

    # Only one script from Phase 2 coder usually (c_t^k replaced)
    script_to_run = candidate_scripts[-1]

    # Check validation cache
    cached_status = check_validation_cache(script_to_run)
    if cached_status == "VALIDATION_FAILED":
        logger.warning("Script previously failed validation. Skipping run.")
        return {
            "inner_iteration": state.get("inner_iteration", 0) + 1,
            "no_improve_count": state.get("no_improve_count", 0) + 1,
        }
        
    # Use dry run settings if debug mode
    run_kwargs = {}
    if config.DEBUG_MODE:
        run_kwargs = {
            "debug_mode": True,
            "timeout": config.DEBUG_CHECK_TIMEOUT_SECONDS,
            "env": {"DRY_RUN": "1", "DRY_RUN_EPOCHS": "1", "DRY_RUN_SAMPLES": "10"}
        }

    # Run the script
    outer_n = int(state.get("outer_iteration", 0))
    inner_m = int(state.get("inner_iteration", 0))  # current attempt index (pre-increment)
    logger.info("Running generated candidate script...")
    run_result = run_script(script_to_run, **run_kwargs)

    # Persist stdout so phase2_error_analysis can parse PREDICTIONS blocks.
    # ckpt_refinement(outer_n, inner_m) is keyed to the current attempt index.
    config.CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    save_checkpoint(
        config.ckpt_refinement(outer_n, inner_m),
        {
            "outer_iteration": outer_n,
            "inner_iteration": inner_m,
            "stdout": run_result.stdout,
            "stderr": run_result.stderr[-2000:],
            "returncode": run_result.returncode,
            "timed_out": run_result.timed_out,
            "duration_ms": round(run_result.duration_ms, 1),
        },
    )

    # Parse metrics
    metrics = parse_metrics(run_result.stdout)
    
    # Parse smoke diagnostics and use it to guard the metrics
    smoke = build_smoke_diagnostics(run_result.stdout, run_result.duration_ms, context="phase2_evaluator")
    if smoke.get("pruned"):
        logger.warning("Smoke diagnostics flagged egregious metrics; discarding.")
        metrics = None

    metrics = guard_metrics(metrics, run_result.duration_ms, context="phase2_evaluator")

    new_metrics_dict = {}
    if metrics is None:
        logger.warning("Degenerate or unparseable metrics from candidate run.")
    else:
        new_metrics_dict = metrics_to_dict(metrics)

    # Store in cache that we ran this successfully
    if cached_status is None:
        store_validation_cache(script_to_run, "VALIDATED")

    # Load current best
    current_best_metrics = {
        "accuracy": state.get("best_accuracy", 0.0),
        "ng_recall": state.get("current_best_score", 0.0), # Assuming this maps to ng_recall based on config
        "miss_rate": state.get("best_miss_rate", 1.0),
        "overkill_rate": state.get("best_overkill_rate", 1.0),
        "f1": state.get("best_f1", 0.0),
    }

    improved = False
    best_updates = {}
    if new_metrics_dict:
        # Check if improvement
        if is_acceptance_improvement(new_metrics_dict, current_best_metrics):
            logger.info("Candidate improved acceptance distance! Updating best state.")
            improved = True
            
            best_updates = {
                "current_best_score": new_metrics_dict.get("ng_recall", 0.0),
                "best_miss_rate": new_metrics_dict.get("miss_rate", 1.0),
                "best_overkill_rate": new_metrics_dict.get("overkill_rate", 1.0),
                "best_accuracy": new_metrics_dict.get("accuracy", 0.0),
                "best_f1": new_metrics_dict.get("f1", 0.0),
                "threshold": new_metrics_dict.get("threshold", 0.5),
            }
            
            # Save pipeline to disk
            best_pipeline = {
                "script": script_to_run,
                "metrics": new_metrics_dict,
                "threshold": new_metrics_dict.get("threshold", 0.5),
            }
            save_checkpoint(config.CKPT_BEST_PIPELINE, best_pipeline)
            best_updates["best_pipeline"] = best_pipeline

    # Update loop states
    inner_iteration = state.get("inner_iteration", 0) + 1
    
    if improved:
        no_improve_count = 0
    else:
        no_improve_count = state.get("no_improve_count", 0) + 1

    # Check exit conditions
    stop_outer_loop = state.get("stop_outer_loop", False)
    
    # Patience based on tier
    current_best_combined = current_best_metrics
    if improved:
        current_best_combined = new_metrics_dict
        
    patience = config.NO_IMPROVE_MAX_CONSTRAINED
    if passes_final_acceptance(current_best_combined):
        patience = config.NO_IMPROVE_MAX
        
    if no_improve_count >= patience:
        logger.info(f"Hit patience cap ({no_improve_count} >= {patience}). Stopping outer loop.")
        stop_outer_loop = True
        
    # Budget check
    if state.get("tokens_used", 0) >= config.TOKEN_BUDGET:
        stop_outer_loop = True

    # Output the required state dict updates
    updates = {
        "inner_iteration": inner_iteration,
        "no_improve_count": no_improve_count,
        "stop_outer_loop": stop_outer_loop,
        "candidate_scores": [{"metrics": new_metrics_dict, "valid": bool(new_metrics_dict)}]
    }
    
    if new_metrics_dict:
        updates["latest_metrics"] = new_metrics_dict
        
    updates.update(best_updates)

    return updates
